version: "3"
services:
  streamlit:
    build: .
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      # mounts local folder into container
      - .:/app
    restart: unless-stopped
